"""Agent-first runtime v2 contracts and orchestration.

This package is intentionally side-effect free: it does not send WhatsApp
messages, persist outbound rows, or mutate customer/lifecycle state.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

from atendia.agent_runtime.action_registry import (
    ActionRegistry,
    default_action_registry,
)
from atendia.agent_runtime.canonical import (
    AliasMap,
    CanonicalProduct,
    CanonicalProductReference,
    QuoteSnapshot,
    SKUIndex,
)
from atendia.agent_runtime.policy_validator import PolicyValidationError, PolicyValidator
from atendia.agent_runtime.schemas import (
    ActionDefinition,
    ActionRequest,
    ActionResult,
    AdvisorBrainDecision,
    AdvisorBrainStateChange,
    AdvisorBrainToolRequest,
    ConversationMemoryContext,
    FieldUpdate,
    LifecycleUpdate,
    TenantRuntimeConfigContext,
    ToolExecutionResult,
    TurnContext,
    TurnInput,
    TurnOutput,
)

_LAZY_EXPORTS = {
    "AGENT_WORKFLOW_EVENT_TYPES": "atendia.agent_runtime.workflow_events",
    "AdvisorBrainProvider": "atendia.agent_runtime.advisor_pipeline",
    "AdvisorFirstAgentProvider": "atendia.agent_runtime.advisor_pipeline",
    "AgentModelProvider": "atendia.agent_runtime.model_provider",
    "AgentRuntime": "atendia.agent_runtime.runtime",
    "AgentWorkflowEvent": "atendia.agent_runtime.workflow_events",
    "AgentWorkflowEventEmitter": "atendia.agent_runtime.workflow_events",
    "AgentRuntimeV2PilotPolicyService": "atendia.agent_runtime.pilot_policy",
    "BusinessEvent": "atendia.agent_runtime.business_events",
    "BusinessEventBundle": "atendia.agent_runtime.business_events",
    "ContextBuilder": "atendia.agent_runtime.context_builder",
    "DeterministicAgentProvider": "atendia.agent_runtime.runtime",
    "DeterministicAdvisorBrain": "atendia.agent_runtime.advisor_pipeline",
    "HumanResponseCandidate": "atendia.agent_runtime.human_response_composer",
    "HumanResponseComposer": "atendia.agent_runtime.human_response_composer",
    "ValidatedResponsePlan": "atendia.agent_runtime.validated_response_plan",
    "ValidatedResponsePlanBuilder": "atendia.agent_runtime.validated_response_plan",
    "MockAgentProvider": "atendia.agent_runtime.model_provider",
    "MandatoryToolApplyResult": "atendia.agent_runtime.mandatory_tools",
    "MandatoryToolEvaluation": "atendia.agent_runtime.mandatory_tools",
    "MandatoryToolGuard": "atendia.agent_runtime.mandatory_tools",
    "NoopToolLayer": "atendia.agent_runtime.advisor_pipeline",
    "OpenAIAgentProvider": "atendia.agent_runtime.model_provider",
    "PostTurnActionExecutor": "atendia.agent_runtime.post_turn_executor",
    "ProviderReliabilityConfig": "atendia.agent_runtime.provider_reliability",
    "ProviderReliabilityLayer": "atendia.agent_runtime.provider_reliability",
    "ProviderRetryExhaustedError": "atendia.agent_runtime.provider_reliability",
    "AgentContextPackage": "atendia.agent_runtime.respond_style_turn_contract",
    "AgentTurnInput": "atendia.agent_runtime.respond_style_turn_contract",
    "AgentTurnRetryInstruction": "atendia.agent_runtime.respond_style_turn_contract",
    "AgentTurnValidationResult": "atendia.agent_runtime.respond_style_turn_contract",
    "FinalTurnDecision": "atendia.agent_runtime.respond_style_turn_contract",
    "LLMActionProposal": "atendia.agent_runtime.respond_style_turn_contract",
    "LLMAgentTurnOutput": "atendia.agent_runtime.respond_style_turn_contract",
    "LLMClaim": "atendia.agent_runtime.respond_style_turn_contract",
    "LLMFieldUpdateProposal": "atendia.agent_runtime.respond_style_turn_contract",
    "LLMHandoffProposal": "atendia.agent_runtime.respond_style_turn_contract",
    "LLMToolCallProposal": "atendia.agent_runtime.respond_style_turn_contract",
    "LLMWorkflowEventProposal": "atendia.agent_runtime.respond_style_turn_contract",
    "TurnKind": "atendia.agent_runtime.respond_style_turn_contract",
    "ValidationErrorItem": "atendia.agent_runtime.respond_style_turn_contract",
    "ContactFieldState": "atendia.agent_runtime.respond_style_context_builder",
    "ContextSnapshotError": "atendia.agent_runtime.respond_style_context_builder",
    "RespondStyleBuiltContext": "atendia.agent_runtime.respond_style_context_builder",
    "RespondStyleContextPackageBuilder": "atendia.agent_runtime.respond_style_context_builder",
    "RespondStyleContextSnapshot": "atendia.agent_runtime.respond_style_context_builder",
    "TranscriptMessage": "atendia.agent_runtime.respond_style_context_builder",
    "ProductAgentRuntime": "atendia.agent_runtime.respond_style_product_agent_runtime",
    "ProductAgentRuntimeInput": "atendia.agent_runtime.respond_style_product_agent_runtime",
    "ProductAgentRuntimeResult": "atendia.agent_runtime.respond_style_product_agent_runtime",
    "ProductAgentRuntimeSnapshotAdapter": (
        "atendia.agent_runtime.respond_style_product_agent_runtime"
    ),
    "ConversationStateSnapshot": (
        "atendia.agent_runtime.respond_style_product_agent_config_adapter"
    ),
    "ConversationStateSource": (
        "atendia.agent_runtime.respond_style_product_agent_config_adapter"
    ),
    "ProductAgentConfigSnapshotAdapter": (
        "atendia.agent_runtime.respond_style_product_agent_config_adapter"
    ),
    "ProductAgentConfigSource": (
        "atendia.agent_runtime.respond_style_product_agent_config_adapter"
    ),
    "ProductAgentPublishedConfig": (
        "atendia.agent_runtime.respond_style_product_agent_config_adapter"
    ),
    "published_config_from_version_payload": (
        "atendia.agent_runtime.respond_style_product_agent_config_adapter"
    ),
    "DeploymentResolution": "atendia.agent_runtime.respond_style_deployment_resolver",
    "DeploymentView": "atendia.agent_runtime.respond_style_deployment_resolver",
    "RespondStyleDeploymentResolver": (
        "atendia.agent_runtime.respond_style_deployment_resolver"
    ),
    "DryFactsToolExecutor": "atendia.agent_runtime.respond_style_dry_facts_executor",
    "ParityDifference": "atendia.agent_runtime.respond_style_parity_gate",
    "ParityGateResult": "atendia.agent_runtime.respond_style_parity_gate",
    "run_parity_gate": "atendia.agent_runtime.respond_style_parity_gate",
    "audit_direct_route_imports": "atendia.agent_runtime.respond_style_route_audit",
    "InMemoryEvidenceSink": "atendia.agent_runtime.respond_style_test_lab_direct",
    "RespondStyleTestLabDirect": "atendia.agent_runtime.respond_style_test_lab_direct",
    "TestLabEvidenceSink": "atendia.agent_runtime.respond_style_test_lab_direct",
    "TestLabScenario": "atendia.agent_runtime.respond_style_test_lab_direct",
    "TestLabScenarioResult": "atendia.agent_runtime.respond_style_test_lab_direct",
    "TestLabTurnEvidence": "atendia.agent_runtime.respond_style_test_lab_direct",
    "COMMANDS_HELP": "atendia.agent_runtime.respond_style_manual_simulator",
    "ManualLiveSimulator": "atendia.agent_runtime.respond_style_manual_simulator",
    "SimulatorOutput": "atendia.agent_runtime.respond_style_manual_simulator",
    "LiveSimulatedChannel": "atendia.agent_runtime.respond_style_live_simulated_channel",
    "SimulatedChannelSummary": (
        "atendia.agent_runtime.respond_style_live_simulated_channel"
    ),
    "SimulatedTurnRecord": "atendia.agent_runtime.respond_style_live_simulated_channel",
    "HardPolicy": "atendia.agent_runtime.respond_style_turn_validator",
    "RespondStyleTurnValidator": "atendia.agent_runtime.respond_style_turn_validator",
    "RespondStyleTurnValidatorConfig": "atendia.agent_runtime.respond_style_turn_validator",
    "default_hard_policies": "atendia.agent_runtime.respond_style_turn_validator",
    "RespondStyleLLMTurnProvider": "atendia.agent_runtime.respond_style_llm_provider",
    "RespondStyleLLMTurnProviderConfig": "atendia.agent_runtime.respond_style_llm_provider",
    "build_respond_style_messages": "atendia.agent_runtime.respond_style_llm_provider",
    "parse_llm_agent_turn_output_json": "atendia.agent_runtime.respond_style_llm_provider",
    "respond_style_llm_json_schema": "atendia.agent_runtime.respond_style_llm_provider",
    "respond_style_system_prompt": "atendia.agent_runtime.respond_style_llm_provider",
    "RespondStyleToolExecutor": "atendia.agent_runtime.respond_style_tool_loop",
    "RespondStyleToolExecutionResult": "atendia.agent_runtime.respond_style_tool_loop",
    "RespondStyleToolLoop": "atendia.agent_runtime.respond_style_tool_loop",
    "RespondStyleToolLoopConfig": "atendia.agent_runtime.respond_style_tool_loop",
    "CopyQualityScore": "atendia.agent_runtime.respond_style_shadow_runner",
    "CurrentPathShadowAdapter": "atendia.agent_runtime.respond_style_shadow_runner",
    "CurrentPathShadowOutput": "atendia.agent_runtime.respond_style_shadow_runner",
    "RespondStylePathShadowOutput": "atendia.agent_runtime.respond_style_shadow_runner",
    "RespondStyleShadowRunner": "atendia.agent_runtime.respond_style_shadow_runner",
    "RespondStyleShadowRunResult": "atendia.agent_runtime.respond_style_shadow_runner",
    "ShadowComparison": "atendia.agent_runtime.respond_style_shadow_runner",
    "compare_shadow_outputs": "atendia.agent_runtime.respond_style_shadow_runner",
    "respond_style_output_from_decision": "atendia.agent_runtime.respond_style_shadow_runner",
    "score_copy": "atendia.agent_runtime.respond_style_shadow_runner",
    "RolloutDecision": "atendia.agent_runtime.rollout_policy",
    "RolloutPolicy": "atendia.agent_runtime.rollout_policy",
    "RolloutPolicyService": "atendia.agent_runtime.rollout_policy",
    "SafeFallbackAgentProvider": "atendia.agent_runtime.model_provider",
    "ChatGPTSemanticInterpreterProvider": "atendia.agent_runtime.semantic_interpreter",
    "DeterministicStateWriter": "atendia.agent_runtime.state_writer",
    "MockSemanticInterpreterProvider": "atendia.agent_runtime.semantic_interpreter",
    "SemanticAdvisorBrain": "atendia.agent_runtime.semantic_interpreter",
    "SemanticInterpretation": "atendia.agent_runtime.semantic_interpreter",
    "SemanticInterpreterProvider": "atendia.agent_runtime.semantic_interpreter",
    "SemanticToolRequest": "atendia.agent_runtime.semantic_interpreter",
    "StructuredRuntimeComposer": "atendia.agent_runtime.advisor_pipeline",
    "StateWriteResult": "atendia.agent_runtime.state_writer",
    "AgentRuntimeShadowService": "atendia.agent_runtime.shadow_service",
    "ShadowRunResult": "atendia.agent_runtime.shadow_service",
    "TenantDomainContract": "atendia.agent_runtime.tenant_domain_contract",
    "TenantDomainContractLoadResult": "atendia.agent_runtime.tenant_domain_contract",
    "TenantDomainField": "atendia.agent_runtime.tenant_domain_contract",
    "TenantDomainTool": "atendia.agent_runtime.tenant_domain_contract",
    "TurnOutputDraft": "atendia.agent_runtime.model_provider",
    "ToolRequirementDecision": "atendia.agent_runtime.mandatory_tools",
    "ToolRequirementRule": "atendia.agent_runtime.mandatory_tools",
    "WorkflowResult": "atendia.agent_runtime.business_events",
    "build_universal_turn_trace": "atendia.agent_runtime.universal_turn_trace",
    "agent_model_provider_enabled": "atendia.agent_runtime.model_provider",
    "attach_universal_turn_trace": "atendia.agent_runtime.universal_turn_trace",
    "build_agent_turn_provider": "atendia.agent_runtime.model_provider",
    "derive_business_event_bundle": "atendia.agent_runtime.business_events",
    "why_answer_from_universal_trace": "atendia.agent_runtime.universal_turn_trace",
}

__all__ = [
    "AGENT_WORKFLOW_EVENT_TYPES",
    "COMMANDS_HELP",
    "ActionDefinition",
    "ActionRegistry",
    "ActionRequest",
    "ActionResult",
    "AdvisorBrainDecision",
    "AdvisorBrainProvider",
    "AdvisorBrainStateChange",
    "AdvisorBrainToolRequest",
    "AdvisorFirstAgentProvider",
    "AgentContextPackage",
    "AgentModelProvider",
    "AgentRuntime",
    "AgentRuntimeShadowService",
    "AgentRuntimeV2PilotPolicyService",
    "AgentTurnInput",
    "AgentTurnRetryInstruction",
    "AgentTurnValidationResult",
    "AgentWorkflowEvent",
    "AgentWorkflowEventEmitter",
    "AliasMap",
    "BusinessEvent",
    "BusinessEventBundle",
    "CanonicalProduct",
    "CanonicalProductReference",
    "ChatGPTSemanticInterpreterProvider",
    "ContactFieldState",
    "ContextBuilder",
    "ContextSnapshotError",
    "ConversationMemoryContext",
    "CopyQualityScore",
    "CurrentPathShadowAdapter",
    "CurrentPathShadowOutput",
    "DeploymentResolution",
    "DeploymentView",
    "DeterministicAdvisorBrain",
    "DeterministicAgentProvider",
    "DeterministicStateWriter",
    "DryFactsToolExecutor",
    "FieldUpdate",
    "FinalTurnDecision",
    "HardPolicy",
    "HumanResponseCandidate",
    "HumanResponseComposer",
    "InMemoryEvidenceSink",
    "LLMActionProposal",
    "LLMAgentTurnOutput",
    "LLMClaim",
    "LLMFieldUpdateProposal",
    "LLMHandoffProposal",
    "LLMToolCallProposal",
    "LLMWorkflowEventProposal",
    "LifecycleUpdate",
    "LiveSimulatedChannel",
    "MandatoryToolApplyResult",
    "MandatoryToolEvaluation",
    "MandatoryToolGuard",
    "ManualLiveSimulator",
    "MockAgentProvider",
    "MockSemanticInterpreterProvider",
    "NoopToolLayer",
    "OpenAIAgentProvider",
    "ParityDifference",
    "ParityGateResult",
    "PolicyValidationError",
    "PolicyValidator",
    "PostTurnActionExecutor",
    "ProductAgentRuntime",
    "ProductAgentRuntimeInput",
    "ProductAgentRuntimeResult",
    "ProviderReliabilityConfig",
    "ProviderReliabilityLayer",
    "ProviderRetryExhaustedError",
    "QuoteSnapshot",
    "RespondStyleBuiltContext",
    "RespondStyleContextPackageBuilder",
    "RespondStyleContextSnapshot",
    "RespondStyleLLMTurnProvider",
    "RespondStyleLLMTurnProviderConfig",
    "RespondStylePathShadowOutput",
    "RespondStyleShadowRunResult",
    "RespondStyleShadowRunner",
    "RespondStyleTestLabDirect",
    "RespondStyleToolExecutionResult",
    "RespondStyleToolExecutor",
    "RespondStyleToolLoop",
    "RespondStyleToolLoopConfig",
    "RespondStyleTurnValidator",
    "RespondStyleTurnValidatorConfig",
    "RolloutDecision",
    "RolloutPolicy",
    "RolloutPolicyService",
    "SKUIndex",
    "SafeFallbackAgentProvider",
    "SemanticAdvisorBrain",
    "SemanticInterpretation",
    "SemanticInterpreterProvider",
    "SemanticToolRequest",
    "ShadowComparison",
    "ShadowRunResult",
    "SimulatedTurnRecord",
    "SimulatorOutput",
    "StateWriteResult",
    "StructuredRuntimeComposer",
    "TenantDomainContract",
    "TenantDomainContractLoadResult",
    "TenantDomainField",
    "TenantDomainTool",
    "TenantRuntimeConfigContext",
    "TestLabEvidenceSink",
    "TestLabScenario",
    "TestLabScenarioResult",
    "TestLabTurnEvidence",
    "ToolExecutionResult",
    "ToolRequirementDecision",
    "ToolRequirementRule",
    "TranscriptMessage",
    "TurnContext",
    "TurnInput",
    "TurnKind",
    "TurnOutput",
    "TurnOutputDraft",
    "ValidatedResponsePlan",
    "ValidatedResponsePlanBuilder",
    "ValidationErrorItem",
    "WorkflowResult",
    "agent_model_provider_enabled",
    "attach_universal_turn_trace",
    "audit_direct_route_imports",
    "build_agent_turn_provider",
    "build_respond_style_messages",
    "build_universal_turn_trace",
    "compare_shadow_outputs",
    "default_action_registry",
    "default_hard_policies",
    "derive_business_event_bundle",
    "parse_llm_agent_turn_output_json",
    "respond_style_llm_json_schema",
    "respond_style_output_from_decision",
    "respond_style_system_prompt",
    "run_parity_gate",
    "score_copy",
    "why_answer_from_universal_trace",
]


def __getattr__(name: str) -> Any:
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module 'atendia.agent_runtime' has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value
