"""006_turn_traces

Revision ID: d890a8df412d
Revises: 294655a35f79
Create Date: 2026-04-30 20:47:12.096820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d890a8df412d"
down_revision: Union[str, Sequence[str], None] = "294655a35f79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "turn_traces",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("inbound_message_id", sa.Uuid(), nullable=True),
        sa.Column("inbound_text", sa.Text(), nullable=True),
        sa.Column("nlu_input", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("nlu_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("nlu_model", sa.String(length=60), nullable=True),
        sa.Column("nlu_tokens_in", sa.Integer(), nullable=True),
        sa.Column("nlu_tokens_out", sa.Integer(), nullable=True),
        sa.Column("nlu_cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("nlu_latency_ms", sa.Integer(), nullable=True),
        sa.Column("state_before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("state_after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("stage_transition", sa.String(length=120), nullable=True),
        sa.Column("composer_input", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("composer_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("composer_model", sa.String(length=60), nullable=True),
        sa.Column("composer_tokens_in", sa.Integer(), nullable=True),
        sa.Column("composer_tokens_out", sa.Integer(), nullable=True),
        sa.Column("composer_cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("composer_latency_ms", sa.Integer(), nullable=True),
        sa.Column("outbound_messages", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "total_cost_usd",
            sa.Numeric(precision=10, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("total_latency_ms", sa.Integer(), nullable=True),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["inbound_message_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_turn_traces_conversation_id"), "turn_traces", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_turn_traces_tenant_id"), "turn_traces", ["tenant_id"], unique=False)
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("turn_trace_id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.String(length=60), nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "called_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["turn_trace_id"], ["turn_traces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tool_calls_tool_name"), "tool_calls", ["tool_name"], unique=False)
    op.create_index(
        op.f("ix_tool_calls_turn_trace_id"), "tool_calls", ["turn_trace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_calls_turn_trace_id"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_tool_name"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index(op.f("ix_turn_traces_tenant_id"), table_name="turn_traces")
    op.drop_index(op.f("ix_turn_traces_conversation_id"), table_name="turn_traces")
    op.drop_table("turn_traces")
    # ### end Alembic commands ###
