"""007_tenant_config

Revision ID: d172f25710e4
Revises: d890a8df412d
Create Date: 2026-04-30 20:50:14.988074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d172f25710e4"
down_revision: Union[str, Sequence[str], None] = "d890a8df412d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant_catalogs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "attrs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "sku", name="uq_tenant_catalogs_tenant_sku"),
    )
    op.create_index(op.f("ix_tenant_catalogs_active"), "tenant_catalogs", ["active"], unique=False)
    op.create_index(
        op.f("ix_tenant_catalogs_tenant_id"), "tenant_catalogs", ["tenant_id"], unique=False
    )
    op.create_table(
        "tenant_faqs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.String(length=500), nullable=False),
        sa.Column("answer", sa.String(length=2000), nullable=False),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenant_faqs_tenant_id"), "tenant_faqs", ["tenant_id"], unique=False)
    op.create_table(
        "tenant_pipelines",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "version", name="uq_tenant_pipelines_tenant_version"),
    )
    op.create_index(
        op.f("ix_tenant_pipelines_active"), "tenant_pipelines", ["active"], unique=False
    )
    op.create_index(
        op.f("ix_tenant_pipelines_tenant_id"), "tenant_pipelines", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenant_pipelines_tenant_id"), table_name="tenant_pipelines")
    op.drop_index(op.f("ix_tenant_pipelines_active"), table_name="tenant_pipelines")
    op.drop_table("tenant_pipelines")
    op.drop_index(op.f("ix_tenant_faqs_tenant_id"), table_name="tenant_faqs")
    op.drop_table("tenant_faqs")
    op.drop_index(op.f("ix_tenant_catalogs_tenant_id"), table_name="tenant_catalogs")
    op.drop_index(op.f("ix_tenant_catalogs_active"), table_name="tenant_catalogs")
    op.drop_table("tenant_catalogs")
    # ### end Alembic commands ###
