"""008_tenant_more_config

Revision ID: 8a8fc618b645
Revises: d172f25710e4
Create Date: 2026-04-30 21:10:02.241420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8a8fc618b645"
down_revision: Union[str, Sequence[str], None] = "d172f25710e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant_branding",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bot_name", sa.String(length=80), server_default=sa.text("'Asistente'"), nullable=False
        ),
        sa.Column(
            "voice",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "default_messages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_table(
        "tenant_templates_meta",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("template_name", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column(
            "language", sa.String(length=10), server_default=sa.text("'es_MX'"), nullable=False
        ),
        sa.Column("body_template", sa.Text(), nullable=False),
        sa.Column(
            "cost_estimate_usd",
            sa.Numeric(precision=10, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("last_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "template_name", "language", name="uq_tenant_templates_meta"
        ),
    )
    op.create_index(
        op.f("ix_tenant_templates_meta_tenant_id"),
        "tenant_templates_meta",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "tenant_tools_config",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.String(length=60), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "tool_name", name="uq_tenant_tools_config"),
    )
    op.create_index(
        op.f("ix_tenant_tools_config_tenant_id"), "tenant_tools_config", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenant_tools_config_tenant_id"), table_name="tenant_tools_config")
    op.drop_table("tenant_tools_config")
    op.drop_index(op.f("ix_tenant_templates_meta_tenant_id"), table_name="tenant_templates_meta")
    op.drop_table("tenant_templates_meta")
    op.drop_table("tenant_branding")
    # ### end Alembic commands ###
