"""009_followups_handoffs

Revision ID: a5b722986579
Revises: 8a8fc618b645
Create Date: 2026-04-30 21:13:20.269334

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5b722986579"
down_revision: Union[str, Sequence[str], None] = "8a8fc618b645"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followups_scheduled",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["tenant_templates_meta.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_followups_scheduled_conversation_id"),
        "followups_scheduled",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_followups_scheduled_run_at"), "followups_scheduled", ["run_at"], unique=False
    )
    op.create_index(
        op.f("ix_followups_scheduled_status"), "followups_scheduled", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_followups_scheduled_tenant_id"), "followups_scheduled", ["tenant_id"], unique=False
    )
    op.create_table(
        "human_handoffs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("assigned_user_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["tenant_users.id"],
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_human_handoffs_conversation_id"),
        "human_handoffs",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_human_handoffs_status"), "human_handoffs", ["status"], unique=False)
    op.create_index(
        op.f("ix_human_handoffs_tenant_id"), "human_handoffs", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_human_handoffs_tenant_id"), table_name="human_handoffs")
    op.drop_index(op.f("ix_human_handoffs_status"), table_name="human_handoffs")
    op.drop_index(op.f("ix_human_handoffs_conversation_id"), table_name="human_handoffs")
    op.drop_table("human_handoffs")
    op.drop_index(op.f("ix_followups_scheduled_tenant_id"), table_name="followups_scheduled")
    op.drop_index(op.f("ix_followups_scheduled_status"), table_name="followups_scheduled")
    op.drop_index(op.f("ix_followups_scheduled_run_at"), table_name="followups_scheduled")
    op.drop_index(op.f("ix_followups_scheduled_conversation_id"), table_name="followups_scheduled")
    op.drop_table("followups_scheduled")
    # ### end Alembic commands ###
