/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as authTurnTracesRouteImport } from './routes/(auth)/turn-traces'
import { Route as authHandoffsRouteImport } from './routes/(auth)/handoffs'
import { Route as authConfigRouteImport } from './routes/(auth)/config'
import { Route as authConversationsConversationIdRouteImport } from './routes/(auth)/conversations.$conversationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authRouteRoute,
} as any)
const authTurnTracesRoute = authTurnTracesRouteImport.update({
  id: '/turn-traces',
  path: '/turn-traces',
  getParentRoute: () => authRouteRoute,
} as any)
const authHandoffsRoute = authHandoffsRouteImport.update({
  id: '/handoffs',
  path: '/handoffs',
  getParentRoute: () => authRouteRoute,
} as any)
const authConfigRoute = authConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => authRouteRoute,
} as any)
const authConversationsConversationIdRoute =
  authConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => authRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/config': typeof authConfigRoute
  '/handoffs': typeof authHandoffsRoute
  '/turn-traces': typeof authTurnTracesRoute
  '/': typeof authIndexRoute
  '/conversations/$conversationId': typeof authConversationsConversationIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/config': typeof authConfigRoute
  '/handoffs': typeof authHandoffsRoute
  '/turn-traces': typeof authTurnTracesRoute
  '/': typeof authIndexRoute
  '/conversations/$conversationId': typeof authConversationsConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(auth)/config': typeof authConfigRoute
  '/(auth)/handoffs': typeof authHandoffsRoute
  '/(auth)/turn-traces': typeof authTurnTracesRoute
  '/(auth)/': typeof authIndexRoute
  '/(auth)/conversations/$conversationId': typeof authConversationsConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/config'
    | '/handoffs'
    | '/turn-traces'
    | '/'
    | '/conversations/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/config'
    | '/handoffs'
    | '/turn-traces'
    | '/'
    | '/conversations/$conversationId'
  id:
    | '__root__'
    | '/(auth)'
    | '/login'
    | '/(auth)/config'
    | '/(auth)/handoffs'
    | '/(auth)/turn-traces'
    | '/(auth)/'
    | '/(auth)/conversations/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/turn-traces': {
      id: '/(auth)/turn-traces'
      path: '/turn-traces'
      fullPath: '/turn-traces'
      preLoaderRoute: typeof authTurnTracesRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/handoffs': {
      id: '/(auth)/handoffs'
      path: '/handoffs'
      fullPath: '/handoffs'
      preLoaderRoute: typeof authHandoffsRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/config': {
      id: '/(auth)/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof authConfigRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/conversations/$conversationId': {
      id: '/(auth)/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof authConversationsConversationIdRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authConfigRoute: typeof authConfigRoute
  authHandoffsRoute: typeof authHandoffsRoute
  authTurnTracesRoute: typeof authTurnTracesRoute
  authIndexRoute: typeof authIndexRoute
  authConversationsConversationIdRoute: typeof authConversationsConversationIdRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authConfigRoute: authConfigRoute,
  authHandoffsRoute: authHandoffsRoute,
  authTurnTracesRoute: authTurnTracesRoute,
  authIndexRoute: authIndexRoute,
  authConversationsConversationIdRoute: authConversationsConversationIdRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
