/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as authConversationsConversationIdRouteImport } from './routes/(auth)/conversations.$conversationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authRouteRoute,
} as any)
const authConversationsConversationIdRoute =
  authConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => authRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof authIndexRoute
  '/conversations/$conversationId': typeof authConversationsConversationIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof authIndexRoute
  '/conversations/$conversationId': typeof authConversationsConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(auth)/': typeof authIndexRoute
  '/(auth)/conversations/$conversationId': typeof authConversationsConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/' | '/conversations/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/conversations/$conversationId'
  id:
    | '__root__'
    | '/(auth)'
    | '/login'
    | '/(auth)/'
    | '/(auth)/conversations/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/conversations/$conversationId': {
      id: '/(auth)/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof authConversationsConversationIdRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authIndexRoute: typeof authIndexRoute
  authConversationsConversationIdRoute: typeof authConversationsConversationIdRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authIndexRoute: authIndexRoute,
  authConversationsConversationIdRoute: authConversationsConversationIdRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
