/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as authUsersRouteImport } from './routes/(auth)/users'
import { Route as authTurnTracesRouteImport } from './routes/(auth)/turn-traces'
import { Route as authHandoffsRouteImport } from './routes/(auth)/handoffs'
import { Route as authCustomersRouteImport } from './routes/(auth)/customers'
import { Route as authConfigRouteImport } from './routes/(auth)/config'
import { Route as authAuditLogRouteImport } from './routes/(auth)/audit-log'
import { Route as authAnalyticsRouteImport } from './routes/(auth)/analytics'
import { Route as authCustomersCustomerIdRouteImport } from './routes/(auth)/customers.$customerId'
import { Route as authConversationsConversationIdRouteImport } from './routes/(auth)/conversations.$conversationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authRouteRoute,
} as any)
const authUsersRoute = authUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => authRouteRoute,
} as any)
const authTurnTracesRoute = authTurnTracesRouteImport.update({
  id: '/turn-traces',
  path: '/turn-traces',
  getParentRoute: () => authRouteRoute,
} as any)
const authHandoffsRoute = authHandoffsRouteImport.update({
  id: '/handoffs',
  path: '/handoffs',
  getParentRoute: () => authRouteRoute,
} as any)
const authCustomersRoute = authCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => authRouteRoute,
} as any)
const authConfigRoute = authConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => authRouteRoute,
} as any)
const authAuditLogRoute = authAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => authRouteRoute,
} as any)
const authAnalyticsRoute = authAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => authRouteRoute,
} as any)
const authCustomersCustomerIdRoute = authCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => authCustomersRoute,
} as any)
const authConversationsConversationIdRoute =
  authConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => authRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/analytics': typeof authAnalyticsRoute
  '/audit-log': typeof authAuditLogRoute
  '/config': typeof authConfigRoute
  '/customers': typeof authCustomersRouteWithChildren
  '/handoffs': typeof authHandoffsRoute
  '/turn-traces': typeof authTurnTracesRoute
  '/users': typeof authUsersRoute
  '/': typeof authIndexRoute
  '/conversations/$conversationId': typeof authConversationsConversationIdRoute
  '/customers/$customerId': typeof authCustomersCustomerIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof authAnalyticsRoute
  '/audit-log': typeof authAuditLogRoute
  '/config': typeof authConfigRoute
  '/customers': typeof authCustomersRouteWithChildren
  '/handoffs': typeof authHandoffsRoute
  '/turn-traces': typeof authTurnTracesRoute
  '/users': typeof authUsersRoute
  '/': typeof authIndexRoute
  '/conversations/$conversationId': typeof authConversationsConversationIdRoute
  '/customers/$customerId': typeof authCustomersCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(auth)/analytics': typeof authAnalyticsRoute
  '/(auth)/audit-log': typeof authAuditLogRoute
  '/(auth)/config': typeof authConfigRoute
  '/(auth)/customers': typeof authCustomersRouteWithChildren
  '/(auth)/handoffs': typeof authHandoffsRoute
  '/(auth)/turn-traces': typeof authTurnTracesRoute
  '/(auth)/users': typeof authUsersRoute
  '/(auth)/': typeof authIndexRoute
  '/(auth)/conversations/$conversationId': typeof authConversationsConversationIdRoute
  '/(auth)/customers/$customerId': typeof authCustomersCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/analytics'
    | '/audit-log'
    | '/config'
    | '/customers'
    | '/handoffs'
    | '/turn-traces'
    | '/users'
    | '/'
    | '/conversations/$conversationId'
    | '/customers/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/audit-log'
    | '/config'
    | '/customers'
    | '/handoffs'
    | '/turn-traces'
    | '/users'
    | '/'
    | '/conversations/$conversationId'
    | '/customers/$customerId'
  id:
    | '__root__'
    | '/(auth)'
    | '/login'
    | '/(auth)/analytics'
    | '/(auth)/audit-log'
    | '/(auth)/config'
    | '/(auth)/customers'
    | '/(auth)/handoffs'
    | '/(auth)/turn-traces'
    | '/(auth)/users'
    | '/(auth)/'
    | '/(auth)/conversations/$conversationId'
    | '/(auth)/customers/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/users': {
      id: '/(auth)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof authUsersRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/turn-traces': {
      id: '/(auth)/turn-traces'
      path: '/turn-traces'
      fullPath: '/turn-traces'
      preLoaderRoute: typeof authTurnTracesRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/handoffs': {
      id: '/(auth)/handoffs'
      path: '/handoffs'
      fullPath: '/handoffs'
      preLoaderRoute: typeof authHandoffsRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/customers': {
      id: '/(auth)/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof authCustomersRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/config': {
      id: '/(auth)/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof authConfigRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/audit-log': {
      id: '/(auth)/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof authAuditLogRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/analytics': {
      id: '/(auth)/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof authAnalyticsRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/customers/$customerId': {
      id: '/(auth)/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof authCustomersCustomerIdRouteImport
      parentRoute: typeof authCustomersRoute
    }
    '/(auth)/conversations/$conversationId': {
      id: '/(auth)/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof authConversationsConversationIdRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authCustomersRouteChildren {
  authCustomersCustomerIdRoute: typeof authCustomersCustomerIdRoute
}

const authCustomersRouteChildren: authCustomersRouteChildren = {
  authCustomersCustomerIdRoute: authCustomersCustomerIdRoute,
}

const authCustomersRouteWithChildren = authCustomersRoute._addFileChildren(
  authCustomersRouteChildren,
)

interface authRouteRouteChildren {
  authAnalyticsRoute: typeof authAnalyticsRoute
  authAuditLogRoute: typeof authAuditLogRoute
  authConfigRoute: typeof authConfigRoute
  authCustomersRoute: typeof authCustomersRouteWithChildren
  authHandoffsRoute: typeof authHandoffsRoute
  authTurnTracesRoute: typeof authTurnTracesRoute
  authUsersRoute: typeof authUsersRoute
  authIndexRoute: typeof authIndexRoute
  authConversationsConversationIdRoute: typeof authConversationsConversationIdRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAnalyticsRoute: authAnalyticsRoute,
  authAuditLogRoute: authAuditLogRoute,
  authConfigRoute: authConfigRoute,
  authCustomersRoute: authCustomersRouteWithChildren,
  authHandoffsRoute: authHandoffsRoute,
  authTurnTracesRoute: authTurnTracesRoute,
  authUsersRoute: authUsersRoute,
  authIndexRoute: authIndexRoute,
  authConversationsConversationIdRoute: authConversationsConversationIdRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
